/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaeecomerce;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import sistemaeecomerce.Classes.Catalogo;
import sistemaeecomerce.Classes.Livro;
import sistemaeecomerce.Classes.MySQL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import sistemaeecomerce.AdminTela;
import sistemaeecomerce.Classes.Query;

/**
 *
 * @author User
 */
public class AltEstoque extends javax.swing.JFrame {

    /**
     * Creates new form AltEstoque ResultSet rs
     */
    ResultSet rs = null;

    public AltEstoque() {
        
        initComponents();
        getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
        
        Query query = new Query();
        
        ArrayList<String> generos1 = new ArrayList();
        
        generos1 = query.MostrarGeneros();
        
        for (int i = 0; i < generos1.size(); i++) {
            gen.addItem(generos1.get(i));
        }
        
        ArrayList<String> autores1 = new ArrayList();
        
        autores1 = query.MostrarAutores();
        
        for (int i = 0; i < autores1.size(); i++) {
            Aut.addItem(autores1.get(i));
        }
        
        ArrayList<String> editoras1 = new ArrayList();
        
        editoras1 = query.MostrarEditoras();
        
        for (int i = 0; i < editoras1.size(); i++) {
            Edi.addItem(editoras1.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Idlivro = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        runidade = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rnome = new javax.swing.JTextPane();
        Preco = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        runi = new javax.swing.JTextPane();
        Alteracao = new javax.swing.JButton();
        Deletar = new javax.swing.JButton();
        gen = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Aut = new javax.swing.JComboBox<>();
        Edi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        jLabel1.setText("Alterar Estoque");

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel2.setText("Digite o ID do produto");

        jLabel3.setText("ID");

        jScrollPane1.setViewportView(Idlivro);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome");

        jLabel5.setText("Preço");

        runidade.setText("Unidades");

        jLabel6.setText("Editora");

        jLabel7.setText("Autor");

        jScrollPane2.setViewportView(rnome);

        Preco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PrecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PrecoFocusLost(evt);
            }
        });
        Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(runi);

        Alteracao.setText("Registrar");
        Alteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlteracaoActionPerformed(evt);
            }
        });

        Deletar.setText("Deletar");
        Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarActionPerformed(evt);
            }
        });

        jLabel8.setText("Genero");

        Aut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutActionPerformed(evt);
            }
        });

        Edi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(runidade))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Preco))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Alteracao)
                                        .addGap(40, 40, 40)
                                        .addComponent(Deletar))
                                    .addComponent(gen, 0, 201, Short.MAX_VALUE)
                                    .addComponent(Aut, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Edi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(runidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deletar)
                    .addComponent(Alteracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Consultar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        AdminTela adm = new AdminTela();
        adm.setVisible(true);
        adm.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoActionPerformed

    private void AlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlteracaoActionPerformed
        Alterar();
    }//GEN-LAST:event_AlteracaoActionPerformed

    private void DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarActionPerformed
        Remover();
    }//GEN-LAST:event_DeletarActionPerformed

    private void AutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutActionPerformed

    private void EdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdiActionPerformed

    }//GEN-LAST:event_EdiActionPerformed

    private void PrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PrecoFocusLost
        String plainText = Preco.getText();
        String formatted = "";
        switch (plainText.length()) {
            case 0:
                formatted = "R$0,00";
                break;
            case 1:
                formatted = "R$0,0" + plainText;
                break;
            case 2:
                formatted = "R$0," + plainText;
                break;
            default:
                String partOne = plainText.substring(0, plainText.length() - 2);
                String partTwo = plainText.substring(plainText.length() - 2, plainText.length());
                int k = 0;
                boolean doSubtring = false;
                for (int i = 0; i < partOne.length(); i++) {
                    
                    if(Character.toString(partOne.charAt(i)).equals("0")) {
                        doSubtring = true;
                        k++;
                    } else {
                        if(doSubtring) {
                            partOne = partOne.substring(k);
                        }
                        break;
                    }
                    
                    if(i == partOne.length() - 1) {
                        if(doSubtring) {
                            partOne = partOne.substring(k - 1);
                        }
                        break;
                    }
                    
                }
                
                formatted = "R$" + partOne + "," + partTwo;
                break;
        }
        
        Preco.setText(formatted);
    }//GEN-LAST:event_PrecoFocusLost

    private void PrecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PrecoFocusGained
        if(Preco.getText().length() > 0) {
            String formatted = Preco.getText();

            String partOne = formatted.substring(2, formatted.length() - 3);
            String partTwo = formatted.substring(formatted.length() - 2, formatted.length());
            String combined = partOne + partTwo;
            
            while(combined.length() != 0 && combined.charAt(0) == '0') {
                combined = combined.replaceFirst("0", "");
            }
            
            Preco.setText(combined);
            
        }
    }//GEN-LAST:event_PrecoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltEstoque().setVisible(true);
            }
        });
    }

    private void Consultar() {
        String sql = "select * from book where id = ?";
        MySQL factory = new MySQL();
        try ( Connection c = factory.obtemConexao()) {
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setString(1, Idlivro.getText());
            rs = ps.executeQuery();
            if (rs.next()) {
                Idlivro.setText(rs.getString(1));
                rnome.setText(rs.getString(2));
                if(rs.getString(3).length() > 0) {
                    String formatted = rs.getString(3);

                    String partOne = formatted.substring(0, formatted.length() - 3);
                    String partTwo = formatted.substring(formatted.length() - 2, formatted.length());
                    String combined = partOne + partTwo;
                    System.out.println(combined);
                    String plainText = combined;
                    formatted = "";
                    switch (plainText.length()) {
                        case 0:
                            formatted = "R$0,00";
                            break;
                        case 1:
                            formatted = "R$0,0" + plainText;
                            break;
                        case 2:
                            formatted = "R$0," + plainText;
                            break;
                        default:
                            partOne = plainText.substring(0, plainText.length() - 2);
                            partTwo = plainText.substring(plainText.length() - 2, plainText.length());
                            int k = 0;
                            boolean doSubtring = false;
                            for (int i = 0; i < partOne.length(); i++) {

                                if(Character.toString(partOne.charAt(i)).equals("0")) {
                                    doSubtring = true;
                                    k++;
                                } else {
                                    if(doSubtring) {
                                        partOne = partOne.substring(k);
                                    }
                                    break;
                                }

                                if(i == partOne.length() - 1) {
                                    if(doSubtring) {
                                        partOne = partOne.substring(k - 1);
                                    }
                                    break;
                                }

                            }

                            formatted = "R$" + partOne + "," + partTwo;
                            break;
                    }

                    Preco.setText(formatted);
                    Aut.setSelectedItem(rs.getString("author"));
                    Edi.setSelectedItem(rs.getString("publisher"));
                    gen.setSelectedItem("genero");
                }
                runi.setText(rs.getString(4));
            } else {
                JOptionPane.showMessageDialog(null, "Livro não Cadastrado!!");
                Idlivro.setText(null);
                rnome.setText(null);
                Preco.setText(null);
                runi.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        /*if(Id.equals(Id)){
            System.out.println("Nome: " + getnome()
                    + "\nPreco: " + getpreco()
                    + "\nUnidade: " + getunidade()
                    + "\nEditora: " + geteditora());
        } else {
            System.out.println("Livro indisponivel !!!");
        }*/
    }

    private void Alterar() {
        String combined = "0.00";
        if(Preco.getText().length() > 0) {
            String formatted = Preco.getText();

            String partOne = formatted.substring(2, formatted.length() - 3);
            String partTwo = formatted.substring(formatted.length() - 2, formatted.length());
            combined = partOne + "." + partTwo;
            
            while(combined.length() != 0 && combined.charAt(0) == '0') {
                combined = combined.replaceFirst("0", "");
            }
        }
        String sql = "UPDATE book SET name=?, price=?, stock = ?, publisher=?, author=? ,genero=? WHERE id=?";
        MySQL factory = new MySQL();
        try ( Connection c = factory.obtemConexao()) {
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setString(1, rnome.getText());
            ps.setString(2, combined);
            ps.setString(3, runi.getText());
            ps.setString(4, (String)Edi.getSelectedItem());
            ps.setString(5, (String) Aut.getSelectedItem());
            ps.setString(7, Idlivro.getText());
            ps.setString(6, (String) gen.getSelectedItem());
            int adicionado = ps.executeUpdate();
            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "Alteração concluída!");
                Idlivro.setText(null);
                rnome.setText(null);
                Preco.setText(null);
                runi.setText(null);
                Edi.addItem(null);
                Aut.addItem(null);
                gen.addItem(null);
            } 
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void Remover() {
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a remoção do livro?",
                "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            String sql = "Delete From book WHERE id=?";
            MySQL factory = new MySQL();
            try ( Connection c = factory.obtemConexao()) {
                PreparedStatement ps = c.prepareStatement(sql);
                ps.setString(1, Idlivro.getText());
                int adicionado = ps.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Remoção concluída!");
                    Idlivro.setText(null);
                    rnome.setText(null);
                    Preco.setText(null);
                    runi.setText(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Erro");
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alteracao;
    private javax.swing.JComboBox<String> Aut;
    private javax.swing.JButton Deletar;
    private javax.swing.JComboBox<String> Edi;
    private javax.swing.JTextPane Idlivro;
    private javax.swing.JTextField Preco;
    private javax.swing.JComboBox<String> gen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane rnome;
    private javax.swing.JTextPane runi;
    private javax.swing.JLabel runidade;
    // End of variables declaration//GEN-END:variables
}
