/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaeecomerce;
import java.util.ArrayList;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;
import sistemaeecomerce.Classes.Livro;

/**
 *
 * @author User
 */
public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
        getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
        javax.swing.JPanel[] lista = {L1, L2, L3, L4, L5, L6, L7, L8};
        javax.swing.JLabel[] titulos = {TituloL1, TituloL2, TituloL3, TituloL4, TituloL5, TituloL6, TituloL7, TituloL8};
        javax.swing.JTextField[] precos = {PrecoL1, PrecoL2, PrecoL3, PrecoL4, PrecoL5, PrecoL6, PrecoL7, PrecoL8};
        javax.swing.JTextField[] editoras = {EditoraL1, EditoraL2, EditoraL3, EditoraL4, EditoraL5, EditoraL6, EditoraL7, EditoraL8};
        javax.swing.JTextField[] autores = {AutorL1, AutorL2, AutorL3, AutorL4, AutorL5, AutorL6, AutorL7, AutorL8};
        
        Livro l = new Livro();

        ArrayList<ArrayList<String>> arrL = l.mostrarLivros();
        
        for (int i = 0; i < lista.length; i++) {
            
            if(i < arrL.size()) {
                String nomes1 = arrL.get(i).get(1);
                String precos1 = arrL.get(i).get(2);
                String unidades1 = arrL.get(i).get(3);
                String editoras1 = arrL.get(i).get(4);
                String autores1 = arrL.get(i).get(5);
                
                if(nomes1.length() > 15) {
                    
                }
                
                titulos[i].setText("<html><p style=\"width:120px\">"+nomes1+"</p></html>");
                precos[i].setText(precos1);
                editoras[i].setText(editoras1);
                autores[i].setText(autores1);
                
            } else {
                lista[i].setVisible(false);
            }  
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        L2 = new javax.swing.JPanel();
        TituloL2 = new javax.swing.JLabel();
        CarrinhoL2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        PrecoL2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        EditoraL2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AutorL2 = new javax.swing.JTextField();
        L3 = new javax.swing.JPanel();
        TituloL3 = new javax.swing.JLabel();
        CarrinhoL3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        PrecoL3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        EditoraL3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        AutorL3 = new javax.swing.JTextField();
        L4 = new javax.swing.JPanel();
        TituloL4 = new javax.swing.JLabel();
        CarrinhoL4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        PrecoL4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        EditoraL4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        AutorL4 = new javax.swing.JTextField();
        L5 = new javax.swing.JPanel();
        TituloL5 = new javax.swing.JLabel();
        CarrinhoL5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        PrecoL5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        EditoraL5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        AutorL5 = new javax.swing.JTextField();
        L6 = new javax.swing.JPanel();
        TituloL6 = new javax.swing.JLabel();
        CarrinhoL6 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        PrecoL6 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        EditoraL6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        AutorL6 = new javax.swing.JTextField();
        L7 = new javax.swing.JPanel();
        TituloL7 = new javax.swing.JLabel();
        CarrinhoL7 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        PrecoL7 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        EditoraL7 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        AutorL7 = new javax.swing.JTextField();
        L8 = new javax.swing.JPanel();
        TituloL8 = new javax.swing.JLabel();
        CarrinhoL8 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        PrecoL8 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        EditoraL8 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        AutorL8 = new javax.swing.JTextField();
        L1 = new javax.swing.JPanel();
        TituloL1 = new javax.swing.JLabel();
        CarrinhoL1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        PrecoL1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        EditoraL1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        AutorL1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BuscaLivro = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        Pesquisar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        VerCadastro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        gen = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Catálogo"));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        L2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TituloL2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TituloL2.setText("Titulo");

        CarrinhoL2.setText("Adicionar ao Carrinho");

        jLabel7.setText("Preço:");

        PrecoL2.setEditable(false);

        jLabel8.setText("Editora");

        EditoraL2.setEditable(false);

        jLabel9.setText("Autor(a)");

        AutorL2.setEditable(false);

        javax.swing.GroupLayout L2Layout = new javax.swing.GroupLayout(L2);
        L2.setLayout(L2Layout);
        L2Layout.setHorizontalGroup(
            L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, L2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CarrinhoL2))
                    .addGroup(L2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(7, 7, 7)
                        .addComponent(AutorL2))
                    .addGroup(L2Layout.createSequentialGroup()
                        .addGroup(L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(L2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addComponent(TituloL2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(L2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(14, 14, 14)
                        .addGroup(L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecoL2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EditoraL2))))
                .addContainerGap())
        );
        L2Layout.setVerticalGroup(
            L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L2Layout.createSequentialGroup()
                .addComponent(TituloL2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PrecoL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(EditoraL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(AutorL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarrinhoL2)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(16, 6, 0, 0);
        jPanel1.add(L2, gridBagConstraints);

        L3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TituloL3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TituloL3.setText("Titulo");

        CarrinhoL3.setText("Adicionar ao Carrinho");

        jLabel10.setText("Preço:");

        PrecoL3.setEditable(false);

        jLabel11.setText("Editora");

        EditoraL3.setEditable(false);

        jLabel12.setText("Autor(a)");

        AutorL3.setEditable(false);

        javax.swing.GroupLayout L3Layout = new javax.swing.GroupLayout(L3);
        L3.setLayout(L3Layout);
        L3Layout.setHorizontalGroup(
            L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, L3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CarrinhoL3))
                    .addGroup(L3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(7, 7, 7)
                        .addComponent(AutorL3))
                    .addGroup(L3Layout.createSequentialGroup()
                        .addGroup(L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(L3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10))
                            .addComponent(TituloL3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(L3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(14, 14, 14)
                        .addGroup(L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecoL3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EditoraL3))))
                .addContainerGap())
        );
        L3Layout.setVerticalGroup(
            L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L3Layout.createSequentialGroup()
                .addComponent(TituloL3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(PrecoL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(EditoraL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(AutorL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarrinhoL3)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 6, 0, 0);
        jPanel1.add(L3, gridBagConstraints);

        L4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TituloL4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TituloL4.setText("Titulo");

        CarrinhoL4.setText("Adicionar ao Carrinho");

        jLabel13.setText("Preço:");

        PrecoL4.setEditable(false);

        jLabel14.setText("Editora");

        EditoraL4.setEditable(false);

        jLabel15.setText("Autor(a)");

        AutorL4.setEditable(false);

        javax.swing.GroupLayout L4Layout = new javax.swing.GroupLayout(L4);
        L4.setLayout(L4Layout);
        L4Layout.setHorizontalGroup(
            L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, L4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CarrinhoL4))
                    .addGroup(L4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(7, 7, 7)
                        .addComponent(AutorL4))
                    .addGroup(L4Layout.createSequentialGroup()
                        .addGroup(L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(L4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel13))
                            .addComponent(TituloL4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(L4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(14, 14, 14)
                        .addGroup(L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecoL4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EditoraL4))))
                .addContainerGap())
        );
        L4Layout.setVerticalGroup(
            L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L4Layout.createSequentialGroup()
                .addComponent(TituloL4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(PrecoL4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(EditoraL4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(AutorL4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarrinhoL4)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(16, 6, 0, 10);
        jPanel1.add(L4, gridBagConstraints);

        L5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TituloL5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TituloL5.setText("Titulo");

        CarrinhoL5.setText("Adicionar ao Carrinho");

        jLabel16.setText("Preço:");

        PrecoL5.setEditable(false);

        jLabel17.setText("Editora");

        EditoraL5.setEditable(false);

        jLabel18.setText("Autor(a)");

        AutorL5.setEditable(false);

        javax.swing.GroupLayout L5Layout = new javax.swing.GroupLayout(L5);
        L5.setLayout(L5Layout);
        L5Layout.setHorizontalGroup(
            L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, L5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CarrinhoL5))
                    .addGroup(L5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(7, 7, 7)
                        .addComponent(AutorL5))
                    .addGroup(L5Layout.createSequentialGroup()
                        .addGroup(L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(L5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel16))
                            .addComponent(TituloL5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(L5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(14, 14, 14)
                        .addGroup(L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecoL5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EditoraL5))))
                .addContainerGap())
        );
        L5Layout.setVerticalGroup(
            L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L5Layout.createSequentialGroup()
                .addComponent(TituloL5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(PrecoL5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(EditoraL5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(AutorL5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarrinhoL5)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 17, 0);
        jPanel1.add(L5, gridBagConstraints);

        L6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TituloL6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TituloL6.setText("Titulo");

        CarrinhoL6.setText("Adicionar ao Carrinho");

        jLabel19.setText("Preço:");

        PrecoL6.setEditable(false);

        jLabel20.setText("Editora");

        EditoraL6.setEditable(false);

        jLabel21.setText("Autor(a)");

        AutorL6.setEditable(false);

        javax.swing.GroupLayout L6Layout = new javax.swing.GroupLayout(L6);
        L6.setLayout(L6Layout);
        L6Layout.setHorizontalGroup(
            L6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(L6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, L6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CarrinhoL6))
                    .addGroup(L6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(7, 7, 7)
                        .addComponent(AutorL6))
                    .addGroup(L6Layout.createSequentialGroup()
                        .addGroup(L6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(L6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel19))
                            .addComponent(TituloL6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(L6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(14, 14, 14)
                        .addGroup(L6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecoL6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EditoraL6))))
                .addGap(6, 6, 6))
        );
        L6Layout.setVerticalGroup(
            L6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L6Layout.createSequentialGroup()
                .addComponent(TituloL6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(PrecoL6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(EditoraL6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(L6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(AutorL6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarrinhoL6)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 17, 0);
        jPanel1.add(L6, gridBagConstraints);

        L7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TituloL7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TituloL7.setText("Titulo");

        CarrinhoL7.setText("Adicionar ao Carrinho");

        jLabel22.setText("Preço:");

        PrecoL7.setEditable(false);

        jLabel23.setText("Editora");

        EditoraL7.setEditable(false);

        jLabel24.setText("Autor(a)");

        AutorL7.setEditable(false);

        javax.swing.GroupLayout L7Layout = new javax.swing.GroupLayout(L7);
        L7.setLayout(L7Layout);
        L7Layout.setHorizontalGroup(
            L7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(L7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, L7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CarrinhoL7))
                    .addGroup(L7Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(14, 14, 14)
                        .addGroup(L7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecoL7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EditoraL7)))
                    .addGroup(L7Layout.createSequentialGroup()
                        .addGroup(L7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(L7Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel22))
                            .addComponent(TituloL7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(L7Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(7, 7, 7)
                        .addComponent(AutorL7)))
                .addContainerGap())
        );
        L7Layout.setVerticalGroup(
            L7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L7Layout.createSequentialGroup()
                .addComponent(TituloL7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(PrecoL7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(EditoraL7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(AutorL7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarrinhoL7)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 17, 0);
        jPanel1.add(L7, gridBagConstraints);

        L8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TituloL8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TituloL8.setText("Titulo");

        CarrinhoL8.setText("Adicionar ao Carrinho");

        jLabel25.setText("Preço:");

        PrecoL8.setEditable(false);

        jLabel26.setText("Editora");

        EditoraL8.setEditable(false);

        jLabel27.setText("Autor(a)");

        AutorL8.setEditable(false);

        javax.swing.GroupLayout L8Layout = new javax.swing.GroupLayout(L8);
        L8.setLayout(L8Layout);
        L8Layout.setHorizontalGroup(
            L8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(L8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, L8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CarrinhoL8))
                    .addGroup(L8Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(7, 7, 7)
                        .addComponent(AutorL8))
                    .addGroup(L8Layout.createSequentialGroup()
                        .addGroup(L8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(L8Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel25))
                            .addComponent(TituloL8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(L8Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(14, 14, 14)
                        .addGroup(L8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecoL8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EditoraL8))))
                .addContainerGap())
        );
        L8Layout.setVerticalGroup(
            L8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L8Layout.createSequentialGroup()
                .addComponent(TituloL8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(PrecoL8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(EditoraL8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(L8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(AutorL8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarrinhoL8)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 17, 10);
        jPanel1.add(L8, gridBagConstraints);

        L1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TituloL1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TituloL1.setText("Titulo");

        CarrinhoL1.setText("Adicionar ao Carrinho");

        jLabel28.setText("Preço:");

        PrecoL1.setEditable(false);

        jLabel29.setText("Editora");

        EditoraL1.setEditable(false);

        jLabel30.setText("Autor(a)");

        AutorL1.setEditable(false);

        javax.swing.GroupLayout L1Layout = new javax.swing.GroupLayout(L1);
        L1.setLayout(L1Layout);
        L1Layout.setHorizontalGroup(
            L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, L1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CarrinhoL1))
                    .addGroup(L1Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(7, 7, 7)
                        .addComponent(AutorL1))
                    .addGroup(L1Layout.createSequentialGroup()
                        .addGroup(L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(L1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel28))
                            .addComponent(TituloL1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(L1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(14, 14, 14)
                        .addGroup(L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecoL1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EditoraL1))))
                .addContainerGap())
        );
        L1Layout.setVerticalGroup(
            L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(L1Layout.createSequentialGroup()
                .addComponent(TituloL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(PrecoL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(EditoraL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(AutorL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarrinhoL1)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(16, 10, 0, 0);
        jPanel1.add(L1, gridBagConstraints);

        jButton1.setText("Meu carrinho");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaeecomerce/Imagens/comprar1.png"))); // NOI18N

        jScrollPane1.setViewportView(BuscaLivro);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel1.setText("Digite qual livro deseja comprar:");

        Pesquisar.setText("Pesquisar");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        Titulo.setText("Bem Vindo!");

        VerCadastro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        VerCadastro.setText("Meu cadastro");
        VerCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerCadastroActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaeecomerce/Imagens/cadastro1.png"))); // NOI18N

        gen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(Pesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(Titulo)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VerCadastro)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)))
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(VerCadastro))))
                .addGap(5, 5, 5)
                .addComponent(Pesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerCadastroActionPerformed
        setVisible(false);
    }//GEN-LAST:event_VerCadastroActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        
        Livro l = new Livro();

        ArrayList<ArrayList<String>> arr = l.pesquisarLivros(BuscaLivro.getText());
        
        javax.swing.JPanel[] lista = {L1, L2, L3, L4, L5, L6, L7, L8};
        javax.swing.JLabel[] titulos = {TituloL1, TituloL2, TituloL3, TituloL4, TituloL5, TituloL6, TituloL7, TituloL8};
        javax.swing.JTextField[] precos = {PrecoL1, PrecoL2, PrecoL3, PrecoL4, PrecoL5, PrecoL6, PrecoL7, PrecoL8};
        javax.swing.JTextField[] editoras = {EditoraL1, EditoraL2, EditoraL3, EditoraL4, EditoraL5, EditoraL6, EditoraL7, EditoraL8};
        javax.swing.JTextField[] autores = {AutorL1, AutorL2, AutorL3, AutorL4, AutorL5, AutorL6, AutorL7, AutorL8};

        ArrayList<ArrayList<String>> arrL = l.pesquisarLivros(BuscaLivro.getText());
        
        for (int i = 0; i < lista.length; i++) {
            
            if(i < arrL.size()) {
                String nomes1 = arrL.get(i).get(1);
                String precos1 = arrL.get(i).get(2);
                String unidades1 = arrL.get(i).get(3);
                String editoras1 = arrL.get(i).get(4);
                String autores1 = arrL.get(i).get(5);
                
                if(nomes1.length() > 15) {
                    
                }
                
                titulos[i].setText("<html><p style=\"width:120px\">"+nomes1+"</p></html>");
                precos[i].setText(precos1);
                editoras[i].setText(editoras1);
                autores[i].setText(autores1);
                
            } else {
                lista[i].setVisible(false);
            }  
        }
    }//GEN-LAST:event_PesquisarActionPerformed

    private void genMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_genMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AutorL1;
    private javax.swing.JTextField AutorL2;
    private javax.swing.JTextField AutorL3;
    private javax.swing.JTextField AutorL4;
    private javax.swing.JTextField AutorL5;
    private javax.swing.JTextField AutorL6;
    private javax.swing.JTextField AutorL7;
    private javax.swing.JTextField AutorL8;
    private javax.swing.JTextPane BuscaLivro;
    private javax.swing.JButton CarrinhoL1;
    private javax.swing.JButton CarrinhoL2;
    private javax.swing.JButton CarrinhoL3;
    private javax.swing.JButton CarrinhoL4;
    private javax.swing.JButton CarrinhoL5;
    private javax.swing.JButton CarrinhoL6;
    private javax.swing.JButton CarrinhoL7;
    private javax.swing.JButton CarrinhoL8;
    private javax.swing.JTextField EditoraL1;
    private javax.swing.JTextField EditoraL2;
    private javax.swing.JTextField EditoraL3;
    private javax.swing.JTextField EditoraL4;
    private javax.swing.JTextField EditoraL5;
    private javax.swing.JTextField EditoraL6;
    private javax.swing.JTextField EditoraL7;
    private javax.swing.JTextField EditoraL8;
    private javax.swing.JPanel L1;
    private javax.swing.JPanel L2;
    private javax.swing.JPanel L3;
    private javax.swing.JPanel L4;
    private javax.swing.JPanel L5;
    private javax.swing.JPanel L6;
    private javax.swing.JPanel L7;
    private javax.swing.JPanel L8;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JTextField PrecoL1;
    private javax.swing.JTextField PrecoL2;
    private javax.swing.JTextField PrecoL3;
    private javax.swing.JTextField PrecoL4;
    private javax.swing.JTextField PrecoL5;
    private javax.swing.JTextField PrecoL6;
    private javax.swing.JTextField PrecoL7;
    private javax.swing.JTextField PrecoL8;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloL1;
    private javax.swing.JLabel TituloL2;
    private javax.swing.JLabel TituloL3;
    private javax.swing.JLabel TituloL4;
    private javax.swing.JLabel TituloL5;
    private javax.swing.JLabel TituloL6;
    private javax.swing.JLabel TituloL7;
    private javax.swing.JLabel TituloL8;
    private javax.swing.JButton VerCadastro;
    private javax.swing.JComboBox<String> gen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
